### PR TITLE
Add 9x16 to crops

### PR DESCRIPTION
**Pull request by blurtime**
It would be nice if one could just add crops 

EDIT: Really love this library btw! :D Only thing I'd recommend is updating the `.podspec`

### CODE REVIEW

**Comment by congnd** [comment]
@blurtime 
Thanks for using this library. 

Just want to ask why do you want to add 9x16 to the default crops? This library already supports custom crops so you can create any crops at any ratios as you like by just conforming to the `FMCroppable` protocol.

**Comment by blurtime** [comment]
3 out of 4 projects I am currently working on require 9x16 and I could bet I am not the only one being increasingly asked to use this format. That's why I thought it might be useful. 

Regarding custom crops, one has to create a new class with e.g. a new enum if one wants to add new crops due to enums (and structs) not being inheritable (I know you can still work around it like so: https://stackoverflow.com/questions/33191532/swift-enum-inheritance but this is rather less elegant) - unless I am missing something, in which case I'd be super happy to hear how I create them on the go, i.e. when defining the available crops. It's rather an idea that would make it easier for a lot of people - especially less experienced swift programmers (like myself) - to define custom crops and might, therefore, boost attractiveness. I hope I am not missing anything. Please let me know if I am. 

It's just an idea and I'm very grateful for the library!

**Comment by blurtime** [comment]
@congnd In that case, I'm very sorry. I didn't know this was possible and thank you for providing the code!
Anyway, feel free to add the code if you think it's a good idea. Sorry for answering so late. I was kind of packed with work and apparently forgot it. 
I would really appreciate if you could update the podspec since the current pod version doesn't seem to function properly as such. 
Thank you for the library!

**Comment by congnd** [comment]
@blurtime 
Thanks for understanding. I'll change the icon after merging this PR and update the pod specs as soon as possible.

**Comment by blurtime** [comment]
Awesome! Thank you - especially for bearing with me! 😅

**Pull request merged**
